-- DROP DATABASE banksystem;
CREATE DATABASE banksystem;
USE banksystem;

-- person information
CREATE TABLE customer_personal_information (
  CUSTOMER_ID VARCHAR(7),
  CUSTOMER_NAME VARCHAR(30),
  DATE_OF_BIRTH DATE,
  GUARDIAN_NAME VARCHAR(30),
  ADDRESS VARCHAR(50),
  CONTACT_NO BIGINT(10),
  MAIL_ID VARCHAR(50),
  GENDER CHAR(1),
  MARITAL_STATUS VARCHAR(10),
  ID_DOC_NO VARCHAR(20),
  CITIZENSHIP VARCHAR(10),
  CONSTRAINT CUST_PERS_INFO_PK PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE customer_reference_info (
  CUSTOMER_ID VARCHAR(7),
  REFERENCE_ACC_NAME VARCHAR(20),
  REFERENCE_ACC_ADDRESS VARCHAR(50),
  REFERENCE_ACC_NO BIGINT(16),
  RELATION VARCHAR(25),
  CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY (CUSTOMER_ID),
  CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES customer_personal_information (CUSTOMER_ID)
);

CREATE TABLE bank_info (
  IFSC_CODE VARCHAR(15),
  BANK_NAME VARCHAR(25),
  BRANCH_NAME VARCHAR(25),
  CONSTRAINT BANK_INFO_PK PRIMARY KEY (IFSC_CODE)
);

CREATE TABLE account_info (
  ACCOUNT_NO BIGINT(16),
  CUSTOMER_ID VARCHAR(7),
  ACCOUNT_TYPE VARCHAR(10),
  REGISTRATION_DATE DATE,
  IFSC_CODE VARCHAR(15),
  INTEREST DECIMAL(7,2),
  INITIAL_DEPOSIT BIGINT(10),
  CONSTRAINT ACC_INFO_PK PRIMARY KEY (ACCOUNT_NO),
  CONSTRAINT ACC_INFO_PERS_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES customer_personal_information (CUSTOMER_ID),
  CONSTRAINT ACC_INFO_BANK_FK FOREIGN KEY (IFSC_CODE) REFERENCES bank_info (IFSC_CODE)
);

-- BANK_INFO
INSERT INTO bank_info (IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES ('IND12233054', 'INDIAN BANK', 'TIRUVALANGADU');
INSERT INTO bank_info (IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES ('HDFC8488979', 'HDFC BANK', 'TIRUVALLUR');
INSERT INTO bank_info (IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES ('ICIT9749043', 'ICICI BANK', 'TNAGAR');
INSERT INTO bank_info (IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES ('SBI1222414', 'SBI BANK', 'TIRUVALLUR');
INSERT INTO bank_info (IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES ('IND12233534', 'INDIAN BANK', 'TIRUVALLUR');

-- customer_personal_information
INSERT INTO customer_personal_information (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID, GENDER, MARITAL_STATUS, ID_DOC_NO, CITIZENSHIP)
VALUES ('CUST001', 'John Doe', '1990-05-15', 'Jane Doe', '123 Main Street', 1234567890, 'john.doe@example.com', 'M', 'Single', 'ID123456', 'US');
INSERT INTO customer_personal_information (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID, GENDER, MARITAL_STATUS, ID_DOC_NO, CITIZENSHIP)
VALUES ('CUST002', 'Jane Smith', '1992-08-20', 'John Smith', '456 Elm Street', 9876543210, 'jane.smith@example.com', 'F', 'Married', 'ID654321', 'US');
INSERT INTO customer_personal_information (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID, GENDER, MARITAL_STATUS, ID_DOC_NO, CITIZENSHIP)
VALUES ('CUST003', 'Sarah Johnson', '1985-12-10', 'Michael Johnson', '789 Oak Avenue', 5555555555, 'sarah.johnson@example.com', 'F', 'Married', 'ID789012', 'UK');
INSERT INTO customer_personal_information (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID, GENDER, MARITAL_STATUS, ID_DOC_NO, CITIZENSHIP)
VALUES ('CUST004', 'Robert Williams', '1993-06-25', 'David Williams', '321 Maple Street', 9998887777, 'robert.williams@example.com', 'M', 'Single', 'ID987654', 'CA');
INSERT INTO customer_personal_information (CUSTOMER_ID, CUSTOMER_NAME, DATE_OF_BIRTH, GUARDIAN_NAME, ADDRESS, CONTACT_NO, MAIL_ID, GENDER, MARITAL_STATUS, ID_DOC_NO, CITIZENSHIP)
VALUES ('CUST005', 'Emily Davis', '1998-03-18', 'Daniel Davis', '567 Pine Street', 7776665555, 'emily.davis@example.com', 'F', 'Single', 'ID567890', 'AU');

-- customer_reference_info
INSERT INTO customer_reference_info (CUSTOMER_ID, REFERENCE_ACC_NAME, REFERENCE_ACC_ADDRESS, REFERENCE_ACC_NO, RELATION)
VALUES 
  ('CUST001', 'Reference Account 1', 'Address 1', 1234567890, 'Relation 1'),
  ('CUST002', 'Reference Account 2', 'Address 2', 2345678901, 'Relation 2'),
  ('CUST003', 'Reference Account 3', 'Address 3', 3456789012, 'Relation 3'),
  ('CUST004', 'Reference Account 4', 'Address 4', 4567890123, 'Relation 4'),
  ('CUST005', 'Reference Account 5', 'Address 5', 5678901234, 'Relation 5');

-- account_info
INSERT INTO account_info (ACCOUNT_NO, CUSTOMER_ID, ACCOUNT_TYPE, REGISTRATION_DATE, IFSC_CODE, INTEREST, INITIAL_DEPOSIT)
VALUES
  (12345678901234, 'CUST001', 'Savings', '2022-01-01', 'IND12233054', 0.5, 10000),
  (23456789012345, 'CUST002', 'Current', '2022-02-01', 'HDFC8488979', 0.3, 5000);

-- Display the inserted records
SELECT * FROM customer_personal_information;
SELECT * FROM customer_reference_info;
SELECT * FROM bank_info;
SELECT * FROM account_info;
    
    --- RETRIVING DATA 
 select  C.CUSTOMER_NAME,B.BANK_NAME,A.ACCOUNT_NO FROM CUSTOMER_PERSONAL_INFORMATION AS C,BANK_INFO AS B, ACCOUNT_INFO AS A;
 --- USING ORDER BY
 select  C.CUSTOMER_NAME,B.BANK_NAME,A.ACCOUNT_NO FROM CUSTOMER_PERSONAL_INFORMATION AS C,BANK_INFO AS B, ACCOUNT_INFO AS A ORDER BY C.CUSTOMER_NAME;
